---
authors:
- admin
date: "2019-12-15"
draft: true
gallery_item:
image:
  caption: ''
  focal_point: "center"
  preview_only: false
lastmod: "2019-12-15T00:00:00-08:00"
summary:  
projects:
tags:
- R
- Twitter
url_slides: ""
title: 'Heatmap for My Twitter Activity Tracking'
---

```{r}
library(rtweet)
library(lubridate)
library(tidyverse)
source("https://raw.githubusercontent.com/iascchen/VisHealth/master/R/calendarHeat.R")
```


```{r eval=FALSE, message=FALSE}
token <- create_token(
  app = "xxx",
  consumer_key = "xxx",
  consumer_secret = "xxx")
```


```{r include=FALSE}
# token <- create_token(
#   app = "rtweet_token_zy",
#   consumer_key = "id8TCZEhdAeSZlYyEl6fzWmQr",
#   consumer_secret = "R0Hgk9TgmsyQlm2fjO3qHYKEr0cf7UE4lnPxm4HEHXUz3Ag6kQ")
```



## Get my timeline
```{r}
targeted_user <- "zhiiiyang"
tweet_list <- get_timeline(targeted_user,n = 3000)
```

## Explore the tweets list 
```{r}
head(tweet_list)
```

#### retweet lists
```{r message=FALSE, warning=FALSE}
tweet_list <- tweet_list %>% 
  mutate(week = week(created_at),
         weekday = wday(created_at, label = TRUE),
         year = year(created_at), 
         month = month(created_at, label = TRUE),
         date = date(created_at)) %>% 
  group_by(year, month) %>% 
  mutate(monthweek = week - min(week) + 1) %>% 
  group_by(date) %>% 
  mutate(activity = n(),
         original = if_else(is.na(reply_to_status_id)==TRUE &
                               is_retweet==FALSE, TRUE, FALSE),
         likes = sum(favorite_count[original==TRUE]),
         retweets = sum(retweet_count[original==TRUE]))
```


```{r message=FALSE, warning=FALSE}
calendarHeat(tweet_list$date, tweet_list$activity, 
             ncolors = 99, color = "g2r", varname="My Tweets & Replies Activitiy")
```